# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

    - repo: https://github.com/commitizen-tools/commitizen
      rev: 3.2.2
      hooks:
          - id: commitizen
          - id: commitizen-branch
            stages: [push]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.3.0
      hooks:
          - id: mypy

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-ast
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-use-type-annotations
          - id: rst-backticks
          - id: rst-directive-colons
          - id: rst-inline-touching-normal

    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black

    # # - repo: https://github.com/PyCQA/bandit
    # #   rev: 1.7.5
    # #   hooks:
    # #       - id: bandit

    - repo: https://github.com/PyCQA/doc8
      rev: v1.1.1
      hooks:
          - id: doc8

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8

    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort

    - repo: https://github.com/PyCQA/prospector
      rev: 1.10.2
      hooks:
          - id: prospector

    - repo: https://github.com/PyCQA/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle

    # - repo: https://github.com/regebro/pyroma
    #   rev: "4.2"
    #   hooks:
    #       - id: pyroma
