name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["~3.7", "~3.8", "~3.9", "~3.10", "~3.11"]
    steps:

      - name: Check out the commit
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the
          # miniconda directory.
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Test with pytest
        run: |
          conda install pytest
          pytest

      - name: Test install
        run: |
          pip install .

      - name: Test uninstall
        run: |
          pip uninstall -y reverse_argparse
